sudo: required

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y openssl parallel


script:
  # Create swarm for explicit testing
  # Make sure that there is a useable ip address as "advertise address" because else the swarm creation fails maybe
  - docker swarm init --advertise-addr `ip addr s | grep global | grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])' | head -n1`
  # Initial build with default parameters
  - docker build -t inspircd:testing .
  # Run all tests from test directory
  - ls tests/*.sh | parallel
